<?php

declare(strict_types=1);

namespace Samushi\Domion\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Samushi\Domion\Helpers\DomainHelpers;
use Symfony\Component\Console\Attribute\AsCommand;

#[AsCommand(
    name: 'domion:link:frontend',
    description: 'Generate JS resolver for Inertia DDD pages',
)]
class LinkFrontend extends Command
{
    public function handle(): int
    {
        $this->info('Generating Inertia Domain Resolver...');

        $pages = DomainHelpers::getInertiaPages();
        
        $resolverPath = base_path('resources/js/domain-resolver.js');
        
        $content = "/**\n * Auto-generated by Domion\n * This file maps Domain aliases to their actual filesystem paths for Inertia/Vite\n */\n\n";
        $content .= "export const domainPages = {\n";
        
        foreach ($pages as $alias => $path) {
            $relativePath = str_replace(base_path() . '/', '../../', $path);
            $content .= "    '{$alias}': () => import('{$relativePath}'),\n";
        }
        
        $content .= "};\n\n";
        $content .= "export const resolveDomainPage = (name) => {\n";
        $content .= "    if (name.includes('::')) {\n";
        $content .= "        const loader = domainPages[name];\n";
        $content .= "        if (!loader) throw new Error(`Domain page [\${name}] not found.`);\n";
        $content .= "        return typeof loader === 'function' ? loader() : loader;\n";
        $content .= "    }\n";
        $content .= "    return null;\n";
        $content .= "};\n";

        File::put($resolverPath, $content);

        $this->components->twoColumnDetail('Resolver File', '<fg=green;options=bold>GENERATED</>');
        $this->info("Path: {$resolverPath}");
        $this->newLine();
        $this->comment('Usage in app.js:');
        $this->comment("import { resolveDomainPage } from './domain-resolver';");
        $this->comment('resolve: (name) => resolveDomainPage(name) || resolvePageComponent(`./Pages/${name}.jsx`, import.meta.glob("./Pages/**/*.jsx")),');

        return self::SUCCESS;
    }
}
